### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sihuiren** [intelligent-environments-lab/CityLearn#99]
## Issue Description

I'm getting an error when I try to reproduce the examples/tutorial.ipynb operation.

## error
Traceback (most recent call last):
  File "E:\PycharmProjects\citylearn\tutorail.py", line 709, in <module>
    _ = tql_model.learn(episodes=tql_episodes)
  File "E:\PycharmProjects\citylearn\venv\lib\site-packages\citylearn\agents\base.py", line 150, in learn
    next_observations, rewards, done, _ = self.env.step(actions)
  File "E:\PycharmProjects\citylearn\venv\lib\site-packages\gym\core.py", line 319, in step
    return self.env.step(action)
  File "E:\PycharmProjects\citylearn\venv\lib\site-packages\gym\core.py", line 456, in step
    return self.env.step(self.action(action))
  File "E:\PycharmProjects\citylearn\venv\lib\site-packages\gym\core.py", line 456, in step
    return self.env.step(self.action(action))
  File "E:\PycharmProjects\citylearn\venv\lib\site-packages\gym\core.py", line 380, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
  File "E:\PycharmProjects\citylearn\venv\lib\site-packages\gym\core.py", line 380, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
ValueError: not enough values to unpack (expected 5, got 4)

## Environment
The environment is the same as the tutorial configuration
python：3.9

## Possible Solution

I tried to change the number of variables in base.py corresponding to the source code, but he gets another error.

###
What should I do?

**Comment by kingsleynweye** [comment]
@sihuiren  see related issues #63 #67.
